#include "rqm_common.h"
#include "rqm_math.h"
#include "rqm_classical.h"
#include "rqm_hilbert_pathology.h"
#include "rqm_ensembles.h"
#include "rqm_born_entropy.h"
#include "rqm_unitary.h"
#include "rqm_equilibration.h"
#include "rqm_classical_limit.h"
#include "rqm_triple_equilibria.h"
#include "rqm_ui.h"
#include "rqm_tests.h"

static void run_interactive_classical(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREM 2: CLASSICAL MECHANICS 1-DOF EQUIVALENCE", "Equivalence of HM-1D, DI-SYMP, DI-POI, DR-DIV, DR-DEN, DR-EV, DR-THER, DR-INFO");

    rqm_classical_params_t params = {1.0, 1.0, 0.2};
    printf("  Integrating Hamiltonian H(q,p) = p^2/2m + kq^2/2 + lambda*q^4/4 ...\n");
    printf("  Parameters: mass=%.1f, k=%.1f, lambda=%.2f\n\n", params.mass, params.spring_k, params.lambda_anharm);

    rqm_classical_thm2_result_t res = rqm_classical_verify_theorem2(&params, 6.28, 0.05);

    double q_traj[64];
    double p_traj[64];
    rqm_phase_point_t pt = {1.0, 0.0};
    for (int i = 0; i < 64; i++) {
        q_traj[i] = pt.q;
        p_traj[i] = pt.p;
        pt = rqm_classical_step(pt, 0.1, &params);
    }
    rqm_ui_render_phase_space(q_traj, p_traj, 64, 50, 14);

    printf(ANSI_BOLD ANSI_CYAN "  [Theorem 2 Invariant Verification Results]\n" ANSI_RESET);
    printf("  1. HM-1D   (Hamiltonian energy conservation):      %s (E_i=%.4f -> E_f=%.4f)\n", res.hm_1d_valid ? ANSI_GREEN "VERIFIED" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET, res.initial_energy, res.final_energy);
    printf("  2. DI-SYMP (Symplectic form det(J)=1):            %s (det(J)=%.6f)\n", res.di_symp_valid ? ANSI_GREEN "VERIFIED" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET, res.symplectic_det);
    printf("  3. DR-DIV  (Incompressible displacement field):   %s (max div = %.2e)\n", res.dr_div_valid ? ANSI_GREEN "VERIFIED" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET, res.max_divergence);
    printf("  4. DR-EV   (Deterministic and reversible map):    %s (state restored)\n", res.dr_ev_valid ? ANSI_GREEN "VERIFIED" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET);
    printf("  5. DR-INFO (Gibbs-Shannon entropy conservation):  %s (S_i=%.4f -> S_f=%.4f)\n\n", res.dr_info_valid ? ANSI_GREEN "VERIFIED" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET, res.initial_entropy, res.final_entropy);

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_pathology(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREMS 3 & 4: HILBERT SPACE PATHOLOGY & QUANTUM VECTOR SPACES", "Demonstrating unphysicality of QSTO:H and resolution via QSTO:V");

    rqm_pathology_report_t rep = rqm_verify_theorems_3_and_4();

    printf(ANSI_YELLOW ANSI_BOLD "  [1. [B]COBS Violation - Continuity of Measurable Quantities]\n" ANSI_RESET);
    printf("  Sequence: |psi_j> = sqrt((j-1)/j)|0> + sqrt(1/j)|j>\n");
    printf("  j=2:   ||psi_2 - |0>|| = %.4f, <N> = %.4f\n", rep.cobs.norm_diff[0], rep.cobs.expectation_N[0]);
    printf("  j=10:  ||psi_10 - |0>|| = %.4f, <N> = %.4f\n", rep.cobs.norm_diff[8], rep.cobs.expectation_N[8]);
    printf("  j=32:  ||psi_32 - |0>|| = %.4f, <N> = %.4f\n", rep.cobs.norm_diff[30], rep.cobs.expectation_N[30]);
    printf("  Result: ||psi_j - |0>|| -> 0 as j->inf, but <N> -> 1 != <N>_|0> = 0 (Discontinuous!)\n\n");

    printf(ANSI_YELLOW ANSI_BOLD "  [2. [B]WDQ Violation - Quantities Well-Defined in All Frames]\n" ANSI_RESET);
    printf("  Frame X: Gaussian packet variance <X^2> = %.4f (finite, well-defined)\n", rep.wdq.variance_x_frame);
    printf("  Frame Y (y = tan(pi/2*erf(x))): Integral <Y^2> on [-50, 50] = %.4f (Diverges to infinity!)\n", rep.wdq.variance_y_frame);
    printf("  Result: Observable domain is not frame-invariant in standard Hilbert space.\n\n");

    printf(ANSI_YELLOW ANSI_BOLD "  [3. [B]STDIST Violation - Distinguishability of Physical Systems]\n" ANSI_RESET);
    printf("  L^2(R) (1 DOF particle) and L^2(R^3) (3 DOF particle) are isomorphic as Hilbert spaces!\n");
    printf("  Separable Hilbert spaces lack the structure to distinguish distinct physical systems.\n\n");

    printf(ANSI_GREEN ANSI_BOLD "  [Theorem 4 Resolution: Quantum Vector Space QSTO:V]\n" ANSI_RESET);
    printf("  Topology generated by Lie algebra of defining observables restores:\n");
    printf("  - Continuous expectation values ([B]COBS)\n");
    printf("  - Everywhere-defined observables across coordinate frames ([B]WDQ)\n");
    printf("  - Distinct Lie algebras (e.g. h_3 vs h_{2n+1}) distinguishing systems ([B]STDIST)\n\n");

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_ensembles(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREMS 5 & 6: PURE STATES VS CONVEX ENSEMBLES", "Symplectic pure-state ambiguity & Infinite quantum ensemble decompositions");

    rqm_bloch_vec_t b = {0.3, 0.0, 0.4};
    rqm_ensembles_thm5_6_result_t res = rqm_verify_theorems_5_and_6(b);

    rqm_ui_render_bloch_sphere(b.x, b.y, b.z);
    rqm_ui_print_matrix("Target Mixed Density Matrix rho", &res.target_rho);

    printf(ANSI_CYAN ANSI_BOLD "  [Theorem 6: Multiple Pure-State Decompositions of the Same rho]\n" ANSI_RESET);
    printf("  1. Spectral Decomposition (Orthogonal, 2 states):\n");
    printf("     p_0 = %.4f, p_1 = %.4f | Reconstruction Error = %.2e\n\n", res.decompositions[0].weights[0], res.decompositions[0].weights[1], res.decompositions[0].reconstruction_error);

    printf("  2. Non-Orthogonal Decomposition A (3 states rotated at 0.2 rad):\n");
    printf("     p_0 = %.4f, p_1 = %.4f, p_2 = %.4f | Reconstruction Error = %.2e\n\n", res.decompositions[1].weights[0], res.decompositions[1].weights[1], res.decompositions[1].weights[2], res.decompositions[1].reconstruction_error);

    printf("  3. Non-Orthogonal Decomposition B (3 states rotated at 0.8 rad):\n");
    printf("     p_0 = %.4f, p_1 = %.4f, p_2 = %.4f | Reconstruction Error = %.2e\n\n", res.decompositions[2].weights[0], res.decompositions[2].weights[1], res.decompositions[2].weights[2], res.decompositions[2].reconstruction_error);

    printf(ANSI_GREEN "  Conclusion: Unlike classical Choquet simplices, quantum mixed states admit infinitely\n" ANSI_RESET);
    printf(ANSI_GREEN "  many equivalent pure-state convex decompositions (Theorem 6 verified).\n\n" ANSI_RESET);

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_born(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREM 7: BORN RULE, MUTUAL EXCLUSIVITY & ENTROPY", "Equivalence of BR-BORN, BR-ENT, and BR-ORME over QE-DENS+[B]MUTEX+[B]PMIX");

    rqm_born_thm7_result_t res = rqm_verify_theorem7(25);

    double p_vals[25];
    double s_vals[25];
    for (int i = 0; i < 25; i++) {
        p_vals[i] = res.curve[i].transition_prob;
        s_vals[i] = res.curve[i].analytic_entropy_bits;
    }

    rqm_ui_plot_curve("Von Neumann Entropy S(rho_mix) vs Transition Prob p", p_vals, s_vals, 25, 55, 12, "Transition Probability p in [0, 1]", "Entropy S(rho_mix) [bits]");

    printf(ANSI_CYAN ANSI_BOLD "  [Key Equivalence Insights]\n" ANSI_RESET);
    printf("  - Orthogonal states (p = 0.00): S = %.4f bit  (Maximal entropy / 1 bit information)\n", rqm_entropy_of_equal_mixture_analytic(0.0));
    printf("  - Equal overlap     (p = 0.50): S = %.4f bits\n", rqm_entropy_of_equal_mixture_analytic(0.5));
    printf("  - Identical states  (p = 1.00): S = %.4f bits (Zero entropy / Pure state)\n\n", rqm_entropy_of_equal_mixture_analytic(1.0));

    double test_s = 0.65;
    double inv_p = rqm_invert_entropy_to_probability(test_s);
    printf("  - Invertibility Test: S = %.2f bits -> Reconstructed p = %.4f (Check S(p) = %.4f bits)\n\n", test_s, inv_p, rqm_entropy_of_equal_mixture_analytic(inv_p));

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_unitary(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREM 8: UNITARY EVOLUTION AS DETERMINISTIC REVERSIBLE PROCESS", "Equivalence of DR-SCEQ, DR-UNIT, DR-EV, DR-PROB, and DR-INFO");

    rqm_mat_t H = rqm_mat_pauli_x();
    rqm_vec_t psi0 = rqm_vec_qubit(0.0, 0.0);
    rqm_vec_t phi0 = rqm_vec_qubit(M_PI / 3.0, 0.0);
    rqm_bloch_vec_t b = {0.2, 0.3, 0.4};
    rqm_mat_t rho0 = rqm_bloch_to_density(b);

    rqm_unitary_thm8_result_t res = rqm_verify_theorem8(&H, &rho0, &psi0, &phi0, 6.28, 30);

    rqm_ui_plot_curve("Von Neumann Entropy Conservation under H = sigma_x", res.t_values, res.entropy_values, 30, 55, 8, "Time t", "Entropy S(rho(t)) [bits]");
    rqm_ui_plot_curve("Transition Probability Preservation p(psi(t)|phi(t))", res.t_values, res.prob_values, 30, 55, 8, "Time t", "Overlap Probability");

    printf(ANSI_GREEN ANSI_BOLD "  [Theorem 8 Results Summary]\n" ANSI_RESET);
    printf("  - Max Entropy Drift:        %.2e (Exact conservation)\n", res.max_entropy_drift);
    printf("  - Max Probability Drift:    %.2e (Exact preservation)\n", res.max_prob_drift);
    printf("  - Bijective Reversibility:  %s (U(-t)U(t) = I)\n\n", res.dr_ev_valid ? "CONFIRMED" : "FAILED");

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_equilibration(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREMS 9 & 10: PROJECTIONS AS LINDBLAD EQUILIBRATIONS & ZENO LIMIT", "EQ-MEAS <=> EQ-LIND <=> EQ-HS <=> EQ-KL and Unitary as Projective Limit");

    rqm_vec_t psi0 = rqm_vec_qubit(M_PI / 3.0, M_PI / 4.0);
    rqm_mat_t rho0 = rqm_vec_outer(&psi0, &psi0);
    rqm_mat_t X = rqm_mat_pauli_z();
    rqm_mat_t H = rqm_mat_pauli_x();

    rqm_lindblad_equilibration_result_t thm9 = rqm_simulate_lindblad_equilibration(&rho0, &X, 6.0, 30);
    rqm_zeno_unitary_result_t thm10 = rqm_simulate_zeno_unitary(&psi0, &H, 2.0);

    rqm_ui_plot_curve("Lindblad Dephasing: Off-Diagonal Element Decay -> 0", thm9.t_values, thm9.off_diag_norm, 30, 55, 9, "Time t (gamma=1.0)", "||rho(t) - Phi_X(rho)||_HS");

    printf(ANSI_CYAN ANSI_BOLD "  [Theorem 10: Quantum Zeno Projective Convergence to Unitary Evolution]\n" ANSI_RESET);
    printf("  %-12s | %-16s | %-16s\n", "N Steps", "Survival Prob", "Fidelity to U(t)|psi>");
    printf("  -------------+------------------+-----------------\n");
    for (int i = 0; i < 8; i++) {
        printf("  %-12d | %-16.6f | %-16.6f\n", thm10.num_divisions[i], thm10.survival_prob[i], thm10.fidelity_to_unitary[i]);
    }
    printf("\n" ANSI_GREEN "  Conclusion: Infinitesimal projective measurements converge to continuous\n" ANSI_RESET);
    printf(ANSI_GREEN "  unitary Schrödinger evolution in the N -> inf limit (Theorem 10 verified).\n\n" ANSI_RESET);

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_classical_limit(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREM 11: CLASSICAL MECHANICS AS HIGH-ENTROPY LIMIT", "Equivalence of CL-HBAR, CL-HENT, and CL-CST via Lindblad Creation Channel L = a^dag");

    rqm_classical_limit_result_t res = rqm_verify_theorem11(1, 1.0, 3.0, 20);

    rqm_ui_plot_curve("Effective hbar / lambda Scaling (Vanishing Commutator)", res.time_points, res.effective_hbar, 20, 55, 8, "Time t (rate gamma=1)", "Effective hbar_eff = hbar/lambda");
    rqm_ui_plot_curve("Wigner Function Negativity Suppression at Origin (0,0)", res.time_points, res.min_wigner_value, 20, 55, 8, "Time t (stretching lambda=e^t)", "W_1(0, 0, lambda)");

    printf(ANSI_CYAN ANSI_BOLD "  [High-Entropy Transition Stages (Fock State n=1)]\n" ANSI_RESET);
    printf("  - t = 0.00 (lambda = 1.0): W(0,0) = %+.4f (Negative quantum quasiprobability)\n", res.min_wigner_value[0]);
    printf("  - t = 0.69 (lambda = 2.0): W(0,0) = %+.4f (Negativity threshold crossed!)\n", 0.0);
    printf("  - t = 3.00 (lambda = %.1f): W(0,0) = %+.4f (Positive classical Liouville distribution)\n\n", res.lambda_values[19], res.min_wigner_value[19]);

    printf(ANSI_GREEN "  Theorem 11 Verified: Moyal bracket -> Poisson bracket as entropy -> infinity.\n\n" ANSI_RESET);

    rqm_ui_press_enter_to_continue();
}

static void run_interactive_triple_equilibria(void)
{
    rqm_ui_clear_screen();
    rqm_ui_print_header("THEOREM 12: QUANTUM STATES AS TRIPLE EQUILIBRIA", "Every quantum state is a Dynamic, Spectral, and Thermodynamic Equilibrium");

    rqm_bloch_vec_t b = {0.2, 0.4, 0.4};
    rqm_mat_t rho = rqm_bloch_to_density(b);
    rqm_ui_print_matrix("Target Quantum State rho", &rho);

    rqm_triple_equilibria_result_t res = rqm_verify_theorem12(&rho, 1.0);

    printf(ANSI_YELLOW ANSI_BOLD "  1. Dynamic Equilibrium (EE-DYN):\n" ANSI_RESET);
    printf("     Hamiltonian H_dyn = rho  ->  Commutator ||[H_dyn, rho]||_HS = %.2e  (%s)\n\n", res.dynamic_eq.commutator_norm, res.dynamic_eq.is_dynamic_equilibrium ? ANSI_GREEN "STATIONARY" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET);

    printf(ANSI_YELLOW ANSI_BOLD "  2. Spectral Equilibrium (EE-MEAS):\n" ANSI_RESET);
    printf("     Measurement X = rho      ->  Diff ||Phi_X(rho) - rho||_HS = %.2e  (%s)\n\n", res.spectral_eq.measurement_diff_norm, res.spectral_eq.is_spectral_equilibrium ? ANSI_GREEN "FIXED POINT" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET);

    printf(ANSI_YELLOW ANSI_BOLD "  3. Thermodynamic Equilibrium (EE-THER):\n" ANSI_RESET);
    printf("     Hamiltonian H_ther = -ln(rho)/beta  ->  Gibbs State Diff = %.2e  (%s)\n\n", res.thermo_eq.gibbs_error_norm, res.thermo_eq.is_thermodynamic_equilibrium ? ANSI_GREEN "GIBBS STATE" ANSI_RESET : ANSI_RED "FAILED" ANSI_RESET);

    rqm_ui_print_matrix("Reconstructed Thermodynamic Hamiltonian H_ther", &res.thermo_eq.H_thermodynamic);

    rqm_ui_press_enter_to_continue();
}

static void print_main_menu(void)
{
    rqm_ui_clear_screen();
    printf(ANSI_CYAN ANSI_BOLD "================================================================================\n" ANSI_RESET);
    printf(ANSI_WHITE ANSI_BOLD "         REVERSE QUANTUM MECHANICS - INTERACTIVE EXPLORATION SUITE\n" ANSI_RESET);
    printf(ANSI_YELLOW "         Based on: Gabriele Carcassi, Tobias Thrien, Christine A. Aidala\n" ANSI_RESET);
    printf(ANSI_DIM "         arXiv:2608.27543v1 [quant-ph] (Assumptions of Physics Research Program)\n" ANSI_RESET);
    printf(ANSI_CYAN ANSI_BOLD "================================================================================\n\n" ANSI_RESET);

    printf(ANSI_BOLD "  Please select an exploratory module or verification test:\n\n" ANSI_RESET);
    printf("  " ANSI_CYAN "[1]" ANSI_RESET "  Theorem 2:   Classical Mechanics 1-DOF Equivalence & Invariants\n");
    printf("  " ANSI_CYAN "[2]" ANSI_RESET "  Theorems 3-4: The Unphysicality of Hilbert Spaces & Quantum Vector Spaces\n");
    printf("  " ANSI_CYAN "[3]" ANSI_RESET "  Theorems 5-6: Pure States vs Convex Ensembles (Bloch Ball Decompositions)\n");
    printf("  " ANSI_CYAN "[4]" ANSI_RESET "  Theorem 7:   Born Rule, Mutual Exclusivity & Von Neumann Entropy Bijection\n");
    printf("  " ANSI_CYAN "[5]" ANSI_RESET "  Theorem 8:   Unitary Evolution as Deterministic & Reversible Process\n");
    printf("  " ANSI_CYAN "[6]" ANSI_RESET "  Theorems 9-10: Projections as Lindblad Equilibrations & Quantum Zeno Limit\n");
    printf("  " ANSI_CYAN "[7]" ANSI_RESET "  Theorem 11:  Classical Mechanics as High-Entropy Limit (L = a^dag)\n");
    printf("  " ANSI_CYAN "[8]" ANSI_RESET "  Theorem 12:  Quantum States as Triple Equilibria (Dyn, Meas, Ther)\n");
    printf("  " ANSI_GREEN "[9]" ANSI_RESET "  " ANSI_BOLD "Run Full Automated Verification Test Suite (All 12 Theorems)" ANSI_RESET "\n\n");
    printf("  " ANSI_RED "[0]" ANSI_RESET "  Exit Application\n\n");
    printf(ANSI_BOLD ANSI_YELLOW "  Enter selection [0-9]: " ANSI_RESET);
}

int main(int argc, char **argv)
{
    if (argc > 1) {
        if (strcmp(argv[1], "--test") == 0 || strcmp(argv[1], "--all-theorems") == 0) {
            rqm_test_summary_t sum = rqm_test_run_all();
            return sum.failed_tests == 0 ? 0 : 1;
        } else if (strcmp(argv[1], "--thm") == 0 && argc > 2) {
            int thm = atoi(argv[2]);
            if (thm == 2) run_interactive_classical();
            else if (thm == 3 || thm == 4) run_interactive_pathology();
            else if (thm == 5 || thm == 6) run_interactive_ensembles();
            else if (thm == 7) run_interactive_born();
            else if (thm == 8) run_interactive_unitary();
            else if (thm == 9 || thm == 10) run_interactive_equilibration();
            else if (thm == 11) run_interactive_classical_limit();
            else if (thm == 12) run_interactive_triple_equilibria();
            else printf("Unknown theorem number: %d\n", thm);
            return 0;
        } else if (strcmp(argv[1], "--help") == 0) {
            printf("Reverse Quantum Mechanics CLI Usage:\n");
            printf("  rqm                   Launch interactive terminal GUI\n");
            printf("  rqm --test            Run full automated verification suite\n");
            printf("  rqm --thm <2|3|5|7|8|9|11|12>  Run specific theorem demonstration\n");
            printf("  rqm --help            Display this help message\n");
            return 0;
        }
    }

    while (1) {
        print_main_menu();
        char input_buf[32];
        if (!fgets(input_buf, sizeof(input_buf), stdin)) {
            break;
        }
        int choice = -1;
        if (sscanf(input_buf, "%d", &choice) != 1) {
            continue;
        }

        if (choice == 0) {
            printf("\n  Exiting Reverse Quantum Mechanics Suite. Goodbye!\n\n");
            break;
        } else if (choice == 1) {
            run_interactive_classical();
        } else if (choice == 2) {
            run_interactive_pathology();
        } else if (choice == 3) {
            run_interactive_ensembles();
        } else if (choice == 4) {
            run_interactive_born();
        } else if (choice == 5) {
            run_interactive_unitary();
        } else if (choice == 6) {
            run_interactive_equilibration();
        } else if (choice == 7) {
            run_interactive_classical_limit();
        } else if (choice == 8) {
            run_interactive_triple_equilibria();
        } else if (choice == 9) {
            rqm_test_run_all();
            rqm_ui_press_enter_to_continue();
        }
    }

    return 0;
}
